/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArmoryRouteImport } from './routes/armory'
import { Route as BattleRouteImport } from './routes/battle'
import { Route as LadderRouteImport } from './routes/ladder'
import { Route as PlayRouteImport } from './routes/play'
import { Route as RollRouteImport } from './routes/roll'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArmoryRoute = ArmoryRouteImport.update({
  id: '/armory',
  path: '/armory',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleRoute = BattleRouteImport.update({
  id: '/battle',
  path: '/battle',
  getParentRoute: () => rootRouteImport,
} as any)
const LadderRoute = LadderRouteImport.update({
  id: '/ladder',
  path: '/ladder',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const RollRoute = RollRouteImport.update({
  id: '/roll',
  path: '/roll',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/armory': typeof ArmoryRoute
  '/battle': typeof BattleRoute
  '/ladder': typeof LadderRoute
  '/play': typeof PlayRoute
  '/roll': typeof RollRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/armory': typeof ArmoryRoute
  '/battle': typeof BattleRoute
  '/ladder': typeof LadderRoute
  '/play': typeof PlayRoute
  '/roll': typeof RollRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/armory': typeof ArmoryRoute
  '/battle': typeof BattleRoute
  '/ladder': typeof LadderRoute
  '/play': typeof PlayRoute
  '/roll': typeof RollRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/armory' | '/battle' | '/ladder' | '/play' | '/roll' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/armory' | '/battle' | '/ladder' | '/play' | '/roll' | '/settings'
  id:
    | '__root__'
    | '/'
    | '/armory'
    | '/battle'
    | '/ladder'
    | '/play'
    | '/roll'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArmoryRoute: typeof ArmoryRoute
  BattleRoute: typeof BattleRoute
  LadderRoute: typeof LadderRoute
  PlayRoute: typeof PlayRoute
  RollRoute: typeof RollRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/armory': {
      id: '/armory'
      path: '/armory'
      fullPath: '/armory'
      preLoaderRoute: typeof ArmoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle': {
      id: '/battle'
      path: '/battle'
      fullPath: '/battle'
      preLoaderRoute: typeof BattleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ladder': {
      id: '/ladder'
      path: '/ladder'
      fullPath: '/ladder'
      preLoaderRoute: typeof LadderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roll': {
      id: '/roll'
      path: '/roll'
      fullPath: '/roll'
      preLoaderRoute: typeof RollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArmoryRoute: ArmoryRoute,
  BattleRoute: BattleRoute,
  LadderRoute: LadderRoute,
  PlayRoute: PlayRoute,
  RollRoute: RollRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
